image: maven:3-jdk-8

cache:
 paths:
 - /root/.m2/repository

stages:
 - build
 - deploy

build:
 stage: build
 script:
 - mvn clean package sonar:sonar -Dsonar.organization=$SONAR_ORG -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN
 artifacts:
     paths:
       - target/*.jar
